language: node_js
node_js:
    - "6"
sudo: required

notifications:
  email:
    recipients:
      - robhang.up@gmail.com
    on_success: never
    on_failure: always

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master