language: node_js
sudo: required

notifications:
  email:
    recipients:
      - robhang.up@gmail.com
    on_success: never
    on_failure: always

before_install:
  - npm i -g npm@latest

cache:
  directories:
    - "node_modules"

branches:
  only:
    - master